### ISSUE TITLE
Repo is gone?

### ISSUE THREAD

**Issue by brewmanandi** [jardicc/am-to-uxp#1]
https://github.com/adobe-uxp/types-photoshop.git doesn't exist anymore.

**Comment by jardicc** [comment]
It is private pre-release Adobe repo. I am still waiting when Adobe will make it public.

**Comment by brewmanandi** [comment]
Thx for info. Any chance you could maybe host a small website that converts executeAction to batchPlay using your code?

**Comment by jardicc** [comment]
I might have something better. A new feature for Alchemist plugin that will send descriptor from ExtendScript into UXP.

**Comment by brewmanandi** [comment]
Very nice

**Comment by jardicc** [comment]
That feature was working and "banned" :-D Or at least that was my impression. :-D 

New types do exists: https://www.npmjs.com/package/@types/photoshop

But I am not sure whether I want to finish this project.
